package dev.zomboidds.bridge.adapter.b42;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.Function;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * The game's printed map labels (town, river, forest, building names): the calls in each map's
 * {@code worldmap-annotations.lua}, which the game runs to put them on the world map and the
 * minimap. That file is generated by the game's map editor and only chains simple calls:
 *
 * <pre>
 *   symbol = symbolsAPI:addUntranslatedText("MapLabel_SaltRiver", "text-water-nofade", 12511, 6734)
 *   symbol:setRGBA(0.000, 0.000, 0.000, 0.000)
 *   symbol:setScale(0.666)
 *   ...
 * </pre>
 *
 * Read here instead of from the game's symbol list, which only holds them once the game's own map
 * has been drawn. "Untranslated" text is a translation key; "translated" text is shown as it is
 * ({@code <br>} is a line break).
 */
final class MapLabels {

    private static final Pattern ADD = Pattern.compile(
            "symbolsAPI:add(Untranslated|Translated)Text\\(\"((?:[^\"\\\\]|\\\\.)*)\"\\s*,\\s*\"[^\"]*\"\\s*,\\s*([-\\d.]+)\\s*,\\s*([-\\d.]+)\\s*\\)"
                    + "|symbolsAPI:addTexture\\(\"([^\"]*)\"\\s*,\\s*([-\\d.]+)\\s*,\\s*([-\\d.]+)");
    private static final Pattern SET = Pattern.compile("symbol:set(\\w+)\\(([^)]*)\\)");

    private MapLabels() {
    }

    /**
     * The labels in one annotations file, in the {@code map_symbols} shape.
     *
     * @param translate a translation key to the player's language
     * @param iconName  a map symbol id to an icon path, or null if unknown
     */
    static List<Map<String, Object>> parse(String lua, Function<String, String> translate, Function<String, String> iconName) {
        List<Map<String, Object>> labels = new ArrayList<>();
        Map<String, Object> current = null;
        for (String line : lua.split("\n")) {
            Matcher add = ADD.matcher(line);
            if (add.find()) {
                current = new LinkedHashMap<>();
                if (add.group(1) != null) {
                    String text = add.group(2).replace("\\\"", "\"");
                    if (add.group(1).equals("Untranslated")) {
                        text = translate.apply(text);
                    }
                    current.put("kind", "text");
                    current.put("text", text.replace("<br>", "\n"));
                    current.put("x", Double.parseDouble(add.group(3)));
                    current.put("y", Double.parseDouble(add.group(4)));
                } else {
                    String icon = iconName.apply(add.group(5));
                    if (icon == null) {
                        current = null;
                        continue;
                    }
                    current.put("kind", "icon");
                    current.put("icon", icon);
                    current.put("x", Double.parseDouble(add.group(6)));
                    current.put("y", Double.parseDouble(add.group(7)));
                }
                current.put("label", true);
                current.put("color", List.of(0.0, 0.0, 0.0, 0.0));
                current.put("scale", 0.666);
                current.put("rotation", 0.0);
                current.put("anchorX", 0.5);
                current.put("anchorY", 0.5);
                current.put("minZoom", 0.0);
                current.put("maxZoom", 24.0);
                labels.add(current);
                continue;
            }
            if (current == null) {
                continue;
            }
            Matcher set = SET.matcher(line);
            if (!set.find()) {
                continue;
            }
            double[] args = numbers(set.group(2));
            switch (set.group(1)) {
                case "RGBA" -> {
                    if (args.length == 4) {
                        current.put("color", List.of(args[0], args[1], args[2], args[3]));
                    }
                }
                case "Scale" -> put(current, "scale", args);
                case "Rotation" -> put(current, "rotation", args);
                case "MinZoom" -> put(current, "minZoom", args);
                case "MaxZoom" -> put(current, "maxZoom", args);
                case "Anchor" -> {
                    if (args.length == 2) {
                        current.put("anchorX", args[0]);
                        current.put("anchorY", args[1]);
                    }
                }
                case "Visible" -> {
                    if (set.group(2).trim().equals("false")) {
                        labels.remove(current);
                        current = null;
                    }
                }
                default -> {
                    // setMatchPerspective, setApplyZoom, setUserDefined, setCollide: not needed on a flat map.
                }
            }
        }
        return labels;
    }

    private static void put(Map<String, Object> symbol, String key, double[] args) {
        if (args.length == 1) {
            symbol.put(key, args[0]);
        }
    }

    private static double[] numbers(String args) {
        String[] parts = args.split(",");
        double[] out = new double[parts.length];
        for (int i = 0; i < parts.length; i++) {
            try {
                out[i] = Double.parseDouble(parts[i].trim());
            } catch (NumberFormatException e) {
                return new double[0];
            }
        }
        return out;
    }
}
